name: Release

on:
  push:
    tags:
      - 'saika*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          
      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 gcc-darwin-x86-64 || true
      
      - name: Build binaries
        run: |
          # Create a directory for the binaries
          mkdir -p build
          
          # Linux build
          GOOS=linux GOARCH=amd64 go build -o build/saika-linux-amd64 ./cmd/saika
          
          # Windows build
          GOOS=windows GOARCH=amd64 go build -o build/saika-windows-amd64.exe ./cmd/saika
          
          # macOS build
          GOOS=darwin GOARCH=amd64 go build -o build/saika-macos-amd64 ./cmd/saika
          
          # List the built files
          ls -la build/
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/saika-linux-amd64
            build/saika-windows-amd64.exe
            build/saika-macos-amd64