name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is important for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Using a stable Go version
      
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o saika-windows-amd64.exe ./cmd/saika
      
      - name: Build for macOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -v -o saika-darwin-amd64 ./cmd/saika
      
      - name: Build for macOS (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -v -o saika-darwin-arm64 ./cmd/saika
      
      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -v -o saika-linux-amd64 ./cmd/saika
      
      - name: Build for Linux (arm64)
        run: GOOS=linux GOARCH=arm64 go build -v -o saika-linux-arm64 ./cmd/saika
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            saika-windows-amd64.exe
            saika-darwin-amd64
            saika-darwin-arm64
            saika-linux-amd64
            saika-linux-arm64
          draft: false
          prerelease: false
          generate_release_notes: true