name: Release

on:
  push:
    tags:
      - 'saika*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # This prevents one failure from canceling other jobs
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: saika-linux-amd64
            asset_path: saika-linux-amd64
          - os: windows-latest
            asset_name: saika-windows-amd64.exe
            asset_path: saika-windows-amd64.exe
          - os: macos-latest
            asset_name: saika-macos-amd64
            asset_path: saika-macos-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Build binary
        run: go build -o ${{ matrix.asset_path }} ./cmd/saika

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_path }}
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/saika-linux-amd64/saika-linux-amd64
            ./artifacts/saika-windows-amd64.exe/saika-windows-amd64.exe
            ./artifacts/saika-macos-amd64/saika-macos-amd64