name: Build and Release

on:
  push:
    # Trigger the workflow when a new tag is pushed
    tags:
      - 'saika*' # Matches v1.0.0, v20.15.10, etc.

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: saika-linux-amd64
          - os: windows-latest
            asset_name: saika-windows-amd64.exe
          - os: macos-latest
            asset_name: saika-macos-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x' # Using Go 1.24 as specified in your go.mod

      - name: Build binary
        run: |
          go build -o ${{ matrix.asset_name }} ./cmd/saika

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            saika-linux-amd64/saika-linux-amd64
            saika-windows-amd64.exe/saika-windows-amd64.exe
            saika-macos-amd64/saika-macos-amd64